version: "3"
services:
  db:
    image: mongo
    restart: always
    volumes:
      - db:/data/db
  web:
    build: "."
    restart: always
    depends_on:
      - db
    environment:
      - DB=mongodb://db
volumes:
  db:
