version: "3"
services:
  web:
    build:
      context: "."
      args:
        GH_TOKEN: ${GH_TOKEN}
    restart: always
    ports:
      - ${PORT}:3000
    environment:
      - VAPID_SUBJECT=${VAPID_SUBJECT}
      - VAPID_PUBLIC=${VAPID_PUBLIC}
      - VAPID_PRIVATE=${VAPID_PRIVATE}
  db:
    image: mongo:latest
    restart: always
    volumes:
      - db:/data/db
volumes:
  db:
